/**
 * The extension's connection to the local annotation bridge.
 *
 * The bridge is a loopback WebSocket server owned by the DSH plugin. It accepts
 * exactly one authenticated peer, and the peer proves itself by presenting a
 * bearer token in its very first frame — before that, the server answers nothing
 * and closes on anything else. Everything in this module exists to keep that
 * connection alive, honest and recoverable across the platform's constraints.
 *
 * ## Why this is harder than a normal WebSocket client
 *
 * An MV3 service worker is not a page. It is started to handle an event and
 * stopped when the platform decides it has been idle, and every live object dies
 * with it: the socket, the timers, the in-memory counters. Three consequences
 * shape the design.
 *
 * 1. **Nothing durable may live in a field.** The token, the last error and the
 *    user-visible pairing state are written to `chrome.storage`, and the worker
 *    re-reads what it needs on every start. A field is a cache, never a source
 *    of truth.
 * 2. **A socket cannot outlive the worker, so it is not kept alive by force.**
 *    The alternative — a repeating alarm that pokes the worker often enough to
 *    stop it sleeping — costs the user battery and memory permanently, to
 *    protect a connection that is only needed when the user is actually
 *    annotating. Instead the connection is treated as opportunistic: the worker
 *    dials on start, reconnects with exponential backoff while it happens to be
 *    awake, and the platform's own event delivery is what wakes it for the next
 *    attempt. The one deliberate exception is documented at
 *    {@link REANCHOR_INTERVAL_MS}: while a socket is *open*, the worker holds a
 *    short repeating alarm, because that is precisely the window in which the
 *    user is annotating and a sleep would silently drop their batch.
 * 3. **A batch must never be lost to a sleep.** {@link BridgeClient.sendBatch}
 *    persists the batch before writing it and only clears it on an explicit
 *    acknowledgement, so a worker recycled mid-flight still has the user's work
 *    when it comes back.
 *
 * ## Pairing
 *
 * The token is generated by the DSH side and shown to the user there. The user
 * types it into the extension's settings, which writes it to `chrome.storage`.
 * This module never generates, guesses or defaults a token: an unpaired
 * extension is idle and says so, rather than hammering a server it cannot
 * authenticate against.
 *
 * @module
 */

import {
  DEFAULT_PORT,
  PROTOCOL_VERSION,
  isAnnotationBatch,
  type AnnotationBatch,
  type BridgeMessage,
  type ExtensionMessage,
} from '../../../src/protocol.ts'

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/** Loopback host the bridge binds. Mirrors the server, which is loopback-only. */
const BRIDGE_HOST = '127.0.0.1'

/** First reconnect delay. Chosen to be short enough to feel instant. */
export const INITIAL_BACKOFF_MS = 1_000

/** Largest reconnect delay. Beyond this a retry storm stops being useful. */
export const MAX_BACKOFF_MS = 30_000

/** Growth factor applied per failed attempt: 1s, 2s, 4s, 8s, then capped. */
const BACKOFF_FACTOR = 2

/**
 * How often the worker re-anchors itself while a socket is open.
 *
 * A worker with an open WebSocket still gets recycled — the socket does not
 * count as activity forever — and a recycled worker takes the socket with it.
 * While the user is annotating that is invisible to them until a batch fails to
 * send, so an open socket is the one state worth spending an alarm on. The
 * period is below the platform's idle threshold, and the alarm is cancelled the
 * moment the socket closes, so the cost is bounded to the annotation session.
 */
export const REANCHOR_INTERVAL_MS = 20_000

/**
 * Liveness probe period.
 *
 * The bridge drops a peer that stops answering, and a laptop that sleeps or a
 * NIC that disappears both produce a socket that looks open long after the peer
 * is gone. Pinging is what turns that into a detectable close.
 */
export const PING_INTERVAL_MS = 25_000

/** Most characters of an error kept for the settings page. */
const MAX_ERROR_LENGTH = 300

// ---------------------------------------------------------------------------
// Storage
// ---------------------------------------------------------------------------

/** Storage keys. Exported so the settings page writes exactly what is read. */
export const STORAGE_KEYS = {
  /** Bearer token the user copied out of DSH. */
  token: 'bridge.token',
  /** Bridge port, so a DSH instance on a non-default port still works. */
  port: 'bridge.port',
  /** Worker health, written for the settings page to read. */
  status: 'bridge.status',
} as const

/** Connection health, as the settings page shows it. */
export type ConnectionState =
  /** No usable token has been entered, so nothing is dialled. */
  | 'unpaired'
  /** A dial is in flight. */
  | 'connecting'
  /** Authenticated and idle. */
  | 'connected'
  /** A dial is scheduled or the socket dropped; a retry is coming. */
  | 'reconnecting'
  /** The bridge refused the token. Retrying cannot help until the user fixes it. */
  | 'unauthorized'
  /** The bridge speaks a different protocol. Retrying cannot help either. */
  | 'incompatible'

/** Why the bridge refused the connection. Mirrors `rejected.reason`. */
export type RejectReason = 'token' | 'version' | 'rate-limit'

/** The worker health record, persisted so it survives a recycle. */
export interface BridgeStatus {
  readonly state: ConnectionState
  /** Human-readable explanation, already bounded and free of secrets. */
  readonly detail: string | null
  /** When the last successful authentication happened, or null. */
  readonly connectedAt: number | null
  /** When the next dial is due, or null when none is scheduled. */
  readonly nextAttemptAt: number | null
  /** How many consecutive failures preceded the current state. */
  readonly attempts: number
  /** Protocol version the bridge reported, or null when unknown. */
  readonly bridgeVersion: number | null
  /** Batches accepted by the bridge since this worker's storage was written. */
  readonly batchesAcked: number
  /** When this record was last written, so a stale one is recognisable. */
  readonly updatedAt: number
}

/** The status a never-started worker reports. */
export const INITIAL_STATUS: BridgeStatus = {
  state: 'unpaired',
  detail: null,
  connectedAt: null,
  nextAttemptAt: null,
  attempts: 0,
  bridgeVersion: null,
  batchesAcked: 0,
  updatedAt: 0,
}

/**
 * A batch awaiting acknowledgement, kept in storage rather than in memory.
 *
 * Only one is held. A queue would have to answer "in what order do two failed
 * batches from two tabs reach the conversation", and that is a product decision
 * this module is not entitled to make; holding the newest batch and letting the
 * user see the failure is the honest behaviour.
 */
export interface PendingBatch {
  readonly batch: AnnotationBatch
  /** The tab the batch came from, so the retry reuses the right frame tree. */
  readonly tabId: number
  /** How many times a write has been attempted, to bound the retrying. */
  readonly attempts: number
}

/** Storage key for the in-flight batch. */
const PENDING_BATCH_KEY = 'bridge.pending'

/** Most times one batch is re-sent before it is reported as undeliverable. */
export const MAX_BATCH_ATTEMPTS = 5

// ---------------------------------------------------------------------------
// Seams
// ---------------------------------------------------------------------------

/**
 * The platform capabilities this module needs.
 *
 * Injected rather than reached for directly so the whole connection state
 * machine can be driven in a test harness by a plain object: a service worker
 * cannot be loaded outside a browser, so a module that only works against the
 * real global would be a module with no unit tests.
 */
export interface BridgeEnvironment {
  /** The storage area holding the token, the port and the status record. */
  readonly storage: {
    get(keys: string): Promise<Record<string, unknown>>
    set(items: Record<string, unknown>): Promise<void>
    remove(keys: string | readonly string[]): Promise<void>
  }
  /** Open a socket. Matches the platform constructor's signature. */
  connect(url: string): WebSocketLike
  /** Schedule a wakeup, or clear one when `info` is null. */
  setAlarm(name: string, info: { when: number; periodInMinutes?: number } | null): void
  /** Current wall-clock time, injectable so backoff is testable without waits. */
  now(): number
  /** This extension's id, reported to the bridge for its connection log. */
  extensionId(): string
  /** Timers. Injected so tests control every delay. */
  setTimeout(handler: () => void, ms: number): number
  clearTimeout(handle: number): void
  setInterval(handler: () => void, ms: number): number
  clearInterval(handle: number): void
  /** Log sink. The worker console is the only reader. */
  log(level: 'info' | 'warn' | 'error', message: string): void
}

/**
 * The part of `WebSocket` this module uses.
 *
 * Declared structurally rather than as the DOM interface because a service
 * worker's socket implementation is not guaranteed to be identical, and because
 * a test double made of a plain class is a truer test than one built by
 * patching a global.
 */
export interface WebSocketLike {
  /** Current state, using the platform's numeric encoding. */
  readonly readyState: number
  /** Send one frame. Throws only when the socket is closing. */
  send(data: string): void
  /** Close politely. */
  close(code?: number, reason?: string): void
  /** Fired once the handshake completes. */
  onopen: ((event: unknown) => void) | null
  /** Fired for every inbound frame. */
  onmessage: ((event: { data: unknown }) => void) | null
  /** Fired when the socket closes, for any reason including a refusal. */
  onclose: ((event: unknown) => void) | null
  /** Fired on a transport error. A close normally follows. */
  onerror: ((event: unknown) => void) | null
}

/** `WebSocket.OPEN`, restated so this module needs no DOM global to compile. */
const SOCKET_OPEN = 1

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Cap a string for storage and logs.
 *
 * Error text can embed a URL or a server banner, and the status record is shown
 * in the settings page and written on every transition, so it is bounded at the
 * boundary rather than at each call site.
 *
 * @param text - the raw text.
 * @returns the text, clipped when long.
 */
function clip(text: string): string {
  return text.length <= MAX_ERROR_LENGTH ? text : `${text.slice(0, MAX_ERROR_LENGTH - 1)}…`
}

/** Whether a value is a record, narrowed for field inspection. */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null
}

/**
 * Compute the next backoff delay.
 *
 * The sequence is 1s, 2s, 4s, 8s, 16s, then 30s forever. It is capped rather
 * than unbounded because a mobile browser throttles a background worker hard,
 * and a delay measured in hours would mean the extension appears permanently
 * dead after a laptop wakes.
 *
 * @param attempt - how many consecutive failures have already happened.
 * @returns the delay in milliseconds, never above {@link MAX_BACKOFF_MS}.
 */
export function backoffDelay(attempt: number): number {
  const safeAttempt = Number.isFinite(attempt) && attempt > 0 ? Math.floor(attempt) : 0
  // Computed by repeated multiplication rather than `2 ** attempt` so that a
  // large attempt count cannot produce `Infinity` before the cap is applied.
  let delay = INITIAL_BACKOFF_MS
  for (let step = 0; step < safeAttempt; step += 1) {
    if (delay >= MAX_BACKOFF_MS) return MAX_BACKOFF_MS
    delay *= BACKOFF_FACTOR
  }
  return Math.min(delay, MAX_BACKOFF_MS)
}

/**
 * Validate a token as the user might have typed it.
 *
 * Whitespace is stripped because copying from a browser page routinely brings a
 * trailing newline with it, and a token that is rejected for an invisible
 * character is indistinguishable to the user from a wrong one. Everything else
 * is the bridge's business: a token with unexpected characters is still sent, so
 * the bridge's own constant-time comparison is what rejects it.
 *
 * @param value - the raw stored value.
 * @returns the usable token, or `null` when there is none.
 */
export function normalizeToken(value: unknown): string | null {
  if (typeof value !== 'string') return null
  const token = value.trim()
  return token === '' ? null : token
}

/**
 * Validate a stored port.
 *
 * @param value - the raw stored value.
 * @returns the port, or {@link DEFAULT_PORT} when absent or unusable.
 */
export function normalizePort(value: unknown): number {
  if (typeof value !== 'number' || !Number.isInteger(value)) return DEFAULT_PORT
  if (value < 1 || value > 65_535) return DEFAULT_PORT
  return value
}

/**
 * Build the socket URL for the bridge.
 *
 * @param port - the loopback port.
 * @returns the URL, e.g. `ws://127.0.0.1:43120`.
 */
export function bridgeUrl(port: number): string {
  return `ws://${BRIDGE_HOST}:${port}`
}

// ---------------------------------------------------------------------------
// Inbound frame narrowing
// ---------------------------------------------------------------------------

/**
 * Narrow one frame from the bridge.
 *
 * The bridge is a local process the user started, which makes it trusted but not
 * omniscient: a version skew or a proxy on the loopback port can put a frame on
 * the wire that this extension does not understand. Unknown frames are ignored
 * rather than treated as fatal, so a newer bridge degrades instead of breaking
 * the older extension.
 *
 * @param value - the result of `JSON.parse` on a frame, or anything else.
 * @returns the narrowed frame, or `undefined`.
 */
export function parseBridgeMessage(value: unknown): BridgeMessage | undefined {
  if (!isRecord(value)) return undefined
  switch (value['type']) {
    case 'welcome': {
      const version = value['version']
      const sessionId = value['sessionId']
      if (typeof version !== 'number') return undefined
      if (sessionId !== null && typeof sessionId !== 'string') return undefined
      return { type: 'welcome', version: version as typeof PROTOCOL_VERSION, sessionId }
    }
    case 'rejected': {
      const reason = value['reason']
      if (reason !== 'token' && reason !== 'version' && reason !== 'rate-limit') return undefined
      return { type: 'rejected', reason }
    }
    case 'pong':
      return { type: 'pong' }
    case 'start-picking': {
      const tabId = value['tabId']
      // `tabId` is optional by design: absent means "whichever tab is in front",
      // which the worker resolves rather than the bridge, because only the
      // extension can see the focused tab.
      if (tabId === undefined) return { type: 'start-picking' }
      if (typeof tabId !== 'number' || !Number.isInteger(tabId)) return undefined
      return { type: 'start-picking', tabId }
    }
    case 'stop-picking':
      return { type: 'stop-picking' }
    case 'submit-ack': {
      const batchId = value['batchId']
      const ok = value['ok']
      const message = value['message']
      if (typeof batchId !== 'string' || typeof ok !== 'boolean') return undefined
      if (message !== undefined && typeof message !== 'string') return undefined
      return message === undefined
        ? { type: 'submit-ack', batchId, ok }
        : { type: 'submit-ack', batchId, ok, message }
    }
    case 'settings': {
      const allowOnline = value['allowOnline']
      if (typeof allowOnline !== 'boolean') return undefined
      return { type: 'settings', allowOnline }
    }
    default:
      return undefined
  }
}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

/** What the worker does when the bridge pushes a command or a setting. */
export interface BridgeHandlers {
  /**
   * Arm picking mode in a tab.
   *
   * @param tabId - the tab named by the bridge, or `null` for "the active tab",
   *   which only the worker can resolve.
   */
  onStartPicking(tabId: number | null): void
  /** Disarm picking mode everywhere it is armed. */
  onStopPicking(): void
  /** Apply an online-access setting pushed by the DSH side. */
  onAllowOnline(allowOnline: boolean): void
  /** A batch reached the conversation. */
  onBatchAcked(batchId: string): void
  /** A batch was refused, with the bridge's explanation. */
  onBatchRejected(batchId: string, message: string): void
}

// ---------------------------------------------------------------------------
// Client
// ---------------------------------------------------------------------------

/**
 * Owns the single socket to the bridge, and the retry policy around it.
 *
 * One instance per worker lifetime. It is created on the worker's `start()` and
 * its socket dies with the worker; the durable parts of its state are in
 * {@link BridgeEnvironment.storage}, which is what makes a recycled worker pick
 * up where the previous one left off.
 *
 * @example
 * ```ts
 * const client = new BridgeClient({ env, handlers })
 * await client.start()      // reads storage, dials if paired
 * client.sendBatch(batch, tabId)  // persists, then writes
 * ```
 */
export class BridgeClient {
  private readonly env: BridgeEnvironment
  private readonly handlers: BridgeHandlers

  // Everything below is a cache over storage. Losing it is always safe.
  private socket: WebSocketLike | null = null
  /** Frames queued while the handshake is still in flight. */
  private readonly outbox: string[] = []
  /** True once `hello` has been written; frames may now be sent directly. */
  private greeted = false
  /**
   * True once the bridge has accepted the handshake with `welcome`.
   *
   * Distinct from {@link greeted}, which only means the token was sent. Between
   * the two the socket is open but unauthenticated, and treating that window as
   * connected would let a batch be queued as if it were deliverable and let the
   * toolbar badge claim a connection the bridge has not granted.
   */
  private authenticated = false
  /** Suppresses reconnection after a refusal that retrying cannot fix. */
  private halted = false
  /** Token currently in use, refreshed when storage changes. */
  private token: string | null = null
  /** Port currently in use. */
  private port: number = DEFAULT_PORT
  /** Consecutive failed dials, reset by a successful authentication. */
  private attempts = 0
  /** Handle for the pending reconnect timer, so it can be cancelled. */
  private retryTimer: number | null = null
  /** Handle for the liveness ping. */
  private pingTimer: number | null = null
  /** Pending batch keyed by id, so an ack can clear the stored copy. */
  private pendingBatchId: string | null = null
  /** Guards against two dials racing (storage change plus alarm, say). */
  private dialing = false
  /** Set by {@link stop} so a teardown cannot trigger a reconnect. */
  private stopped = false

  /**
   * @param options - the platform seams and the worker's push handlers.
   */
  constructor(options: { env: BridgeEnvironment; handlers: BridgeHandlers }) {
    this.env = options.env
    this.handlers = options.handlers
  }

  // -------------------------------------------------------------------------
  // Lifecycle
  // -------------------------------------------------------------------------

  /**
   * Read durable state and dial if the extension is paired.
   *
   * Safe to call on every worker start: a worker can be started many times for
   * one user action, and a second start while a socket is live is a no-op.
   *
   * @returns a promise that settles once the first dial has been initiated,
   *   which is not the same as connected.
   */
  async start(): Promise<void> {
    this.stopped = false
    await this.reloadConfiguration()
    if (this.token === null) {
      await this.writeStatus('unpaired', 'No pairing token has been entered yet.', null)
      return
    }
    // A refused credential is not retried automatically: the user has to change
    // something first, and a retry loop would only generate noise in the
    // bridge's log while they go and find the right token.
    if (this.halted) return
    this.dial()
  }

  /**
   * Close the socket and cancel every timer.
   *
   * Called when the extension is disabled or the worker is being torn down on
   * purpose. It does NOT clear the token or the pending batch: the next worker
   * start is expected to continue the same session.
   */
  stop(): void {
    this.stopped = true
    this.clearTimers()
    this.env.setAlarm('keepalive', null)
    const socket = this.socket
    this.socket = null
    this.greeted = false
    this.authenticated = false
    this.outbox.length = 0
    if (socket !== null) {
      // Detach before closing so the close handler does not schedule a retry
      // for a shutdown the caller asked for.
      socket.onopen = null
      socket.onmessage = null
      socket.onclose = null
      socket.onerror = null
      try {
        socket.close(1000, 'extension stopping')
      } catch {
        // A socket already closing throws here and there is nothing to do.
      }
    }
  }

  /**
   * Re-read the token and port, applying a change made in the settings page.
   *
   * A changed token always forces a fresh dial, because the old socket was
   * authenticated with a credential that is no longer the current one.
   *
   * @returns a promise that settles after storage has been read.
   */
  async reloadConfiguration(): Promise<void> {
    const stored = await this.env.storage.get(`${STORAGE_KEYS.token}/${STORAGE_KEYS.port}`)
    const token = normalizeToken(stored[STORAGE_KEYS.token])
    const port = normalizePort(stored[STORAGE_KEYS.port])

    const changed = token !== this.token || port !== this.port
    this.token = token
    this.port = port

    if (!changed) return
    // A new credential clears the previous refusal: the user has acted, so the
    // halt condition no longer applies.
    this.halted = false
    this.attempts = 0
    if (token === null) {
      this.handlers.onStopPicking()
      await this.writeStatus('unpaired', 'The pairing token was cleared.', null)
      return
    }
    if (this.socket !== null) {
      // Reconnect rather than re-authenticate: the protocol accepts a `hello`
      // only as the first frame on a fresh socket.
      this.teardownSocket('configuration changed')
    }
    // Dialled unconditionally, including straight after a refusal. A `token`
    // rejection closes the socket itself, so the previous branch is not reached
    // in exactly the case this method exists to serve — the user correcting the
    // token and expecting the extension to notice without a restart.
    this.dial()
  }

  /**
   * Whether the bridge has accepted this extension's handshake.
   *
   * Not the same as "a socket exists": the interval between writing `hello` and
   * receiving `welcome` is one in which the bridge has promised nothing, and
   * callers that gate user-visible behaviour on connectivity must not treat it
   * as connected.
   */
  isConnected(): boolean {
    return this.authenticated && this.socket !== null && this.socket.readyState === SOCKET_OPEN
  }

  /** The port currently in use, for the settings page. */
  currentPort(): number {
    return this.port
  }

  // -------------------------------------------------------------------------
  // Outbound
  // -------------------------------------------------------------------------

  /**
   * Send one batch, persisting it first so a worker recycle cannot lose it.
   *
   * The batch is written to storage before any socket call. If the worker is
   * stopped between the two, the stored copy is still there and
   * {@link retryPending} re-sends it on the next start — which is the difference
   * between a user losing their annotations to a background sleep and not.
   *
   * Delivery has exactly ONE path: the stored record, drained by
   * {@link retryPending}. This method deliberately does not also write the frame
   * directly, because "persist and send" plus "on connect, send whatever is
   * stored" would submit the same batch twice whenever a socket happened to be
   * ready — and duplicated annotations in the conversation are a worse failure
   * than a batch that arrives one round-trip later.
   *
   * @param batch - the validated batch to deliver.
   * @param tabId - the tab it came from, kept for the retry path.
   * @returns a promise that settles once the batch has been persisted and any
   *   delivery attempt for it has been made.
   */
  async sendBatch(batch: AnnotationBatch, tabId: number): Promise<void> {
    const pending: PendingBatch = { batch, tabId, attempts: 0 }
    await this.env.storage.set({ [PENDING_BATCH_KEY]: pending })
    this.pendingBatchId = batch.batchId

    if (this.isConnected()) {
      // Delivered through the stored record so the attempt counter advances and
      // an acknowledgement has something to clear.
      await this.retryPending()
      return
    }
    // Not an error the user has to see: the batch is stored, and the connect
    // path will drain it. The status page shows `reconnecting`.
    this.env.log('warn', `[dsh-annotate] batch ${batch.batchId} stored: no authenticated socket yet`)
  }

  /**
   * Re-send a batch that was persisted but never acknowledged.
   *
   * Called on every worker start. It deliberately does nothing while a socket is
   * still connecting: the batch is already stored, and sending it twice on the
   * same connection would duplicate the annotations in the conversation.
   *
   * @returns a promise that settles once the stored batch has been inspected.
   */
  async retryPending(): Promise<void> {
    if (!this.isConnected()) return
    const stored = await this.env.storage.get(PENDING_BATCH_KEY)
    const pending = readPendingBatch(stored[PENDING_BATCH_KEY])
    if (pending === null) return

    if (pending.attempts >= MAX_BATCH_ATTEMPTS) {
      // Reported once and then dropped: a batch the bridge will not take is not
      // made deliverable by trying forever, and holding it would block every
      // later batch behind it.
      this.env.log('error', `[dsh-annotate] dropping batch ${pending.batch.batchId} after ${pending.attempts} attempts`)
      this.handlers.onBatchRejected(pending.batch.batchId, 'The bridge did not accept this batch after several attempts.')
      await this.clearPending()
      return
    }

    const next: PendingBatch = { batch: pending.batch, tabId: pending.tabId, attempts: pending.attempts + 1 }
    await this.env.storage.set({ [PENDING_BATCH_KEY]: next })
    this.pendingBatchId = pending.batch.batchId
    this.write({ type: 'submit', batch: pending.batch })
  }

  /**
   * Announce the page the user is annotating.
   *
   * Best-effort by design: the bridge uses this only to title its own log, and a
   * dropped announcement has no bearing on whether annotations arrive.
   *
   * @param tabId - the tab id.
   * @param url - the page URL.
   * @param title - the page title.
   */
  announcePage(tabId: number, url: string, title: string): void {
    this.write({ type: 'page-picked', tabId, url, title })
  }

  /**
   * Send a liveness probe.
   *
   * The protocol has no client-side `pong`, so the bridge treats any inbound
   * frame as proof of life; a ping is the cheapest such frame.
   */
  ping(): void {
    this.write({ type: 'ping' })
  }

  // -------------------------------------------------------------------------
  // Connection
  // -------------------------------------------------------------------------

  /** Open a socket and arm its handlers. */
  private dial(): void {
    if (this.stopped || this.halted || this.dialing) return
    if (this.socket !== null) return
    if (this.token === null) return

    this.dialing = true
    const url = bridgeUrl(this.port)
    this.env.log('info', `[dsh-annotate] dialling ${url}`)

    let socket: WebSocketLike
    try {
      socket = this.env.connect(url)
    } catch (error: unknown) {
      // A malformed URL or a blocked scheme throws synchronously. Treated as a
      // failed attempt so the backoff sequence still runs.
      this.dialing = false
      void this.scheduleRetry(error instanceof Error ? error.message : String(error), 'connecting')
      return
    }

    this.socket = socket
    this.greeted = false
    this.authenticated = false
    void this.writeStatus(this.attempts === 0 ? 'connecting' : 'reconnecting', null, null)

    socket.onopen = () => {
      this.dialing = false
      // The handshake is the one place the token is sent. It goes first, before
      // anything else, because the bridge closes a socket that speaks out of
      // turn rather than answering an unauthenticated frame.
      this.greeted = true
      this.sendNow({
        type: 'hello',
        version: PROTOCOL_VERSION,
        token: this.token ?? '',
        extensionId: this.env.extensionId(),
      })
    }

    socket.onmessage = (event) => {
      const text = typeof event.data === 'string' ? event.data : ''
      if (text === '') return
      this.handleFrame(text)
    }

    socket.onerror = () => {
      // An error is always followed by a close, which is where the retry is
      // scheduled; logging here would double every failure.
      this.env.log('warn', '[dsh-annotate] socket error')
    }

    socket.onclose = (event) => {
      this.dialing = false
      const code = closeCodeOf(event)
      // Whether the handshake got as far as a `hello`. This decides which story
      // the user is told: "the bridge is not running" and "the bridge hung up on
      // us" are different problems with different fixes.
      const wasGreeted = this.greeted
      this.socket = null
      this.greeted = false
      this.authenticated = false
      this.outbox.length = 0
      this.clearPing()
      // Released here as well as in teardown: the keepalive alarm exists to hold
      // the worker awake for an OPEN socket, so leaving it armed after a drop
      // would pin the worker awake permanently to protect nothing.
      this.env.setAlarm('keepalive', null)

      if (this.stopped) return
      // The bridge's own close codes distinguish "you are not who you say" from
      // "the network went away". Only the first is worth telling the user about;
      // the second is handled by reconnecting, which is what they actually want.
      if (this.halted) return
      const detail = wasGreeted
        ? `The bridge closed the connection${code === null ? '' : ` (code ${code})`}.`
        : 'The bridge is not reachable on its loopback port.'
      void this.scheduleRetry(detail, 'reconnecting')
    }
  }

  /**
   * Route one authenticated frame.
   *
   * @param text - the decoded frame.
   */
  private handleFrame(text: string): void {
    let parsed: unknown
    try {
      parsed = JSON.parse(text)
    } catch {
      this.env.log('warn', '[dsh-annotate] dropped an unparseable frame from the bridge')
      return
    }

    const message = parseBridgeMessage(parsed)
    if (message === undefined) {
      // Forward compatibility: a newer bridge may send frames this build does
      // not know, and dropping them keeps the connection usable.
      this.env.log('warn', '[dsh-annotate] ignored an unrecognised frame from the bridge')
      return
    }

    switch (message.type) {
      case 'welcome':
        void this.onWelcome(message.version)
        break
      case 'rejected':
        void this.onRejected(message.reason)
        break
      case 'submit-ack':
        void this.onSubmitAck(message.batchId, message.ok, message.message)
        break
      case 'start-picking':
        this.handlers.onStartPicking(message.tabId ?? null)
        break
      case 'stop-picking':
        this.handlers.onStopPicking()
        break
      case 'settings':
        this.handlers.onAllowOnline(message.allowOnline)
        break
      case 'pong':
        // Liveness is proven by the frame arriving; there is nothing to record.
        break
    }
  }

  /**
   * Apply a successful authentication.
   *
   * @param version - the protocol version the bridge reported.
   */
  private async onWelcome(version: number): Promise<void> {
    // The backoff is reset only here, not on every socket open: a server that
    // accepts connections and then refuses them would otherwise be dialled once
    // per second forever.
    this.attempts = 0
    this.halted = false
    this.authenticated = true
    await this.writeStatus('connected', null, version)

    // Anything that queued while the handshake was in flight goes out now, in
    // the order it was produced.
    const queued = this.outbox.splice(0, this.outbox.length)
    for (const frame of queued) this.sendRaw(frame)

    this.startPing()
    // The socket is the state worth paying for: see {@link REANCHOR_INTERVAL_MS}.
    this.env.setAlarm('keepalive', { when: this.env.now() + REANCHOR_INTERVAL_MS, periodInMinutes: REANCHOR_INTERVAL_MS / 60_000 })

    await this.retryPending()
  }

  /**
   * Apply a refusal.
   *
   * The three reasons are genuinely different situations for the user, so they
   * are not collapsed into one "connection failed" state:
   *
   * - `token`: the user pasted the wrong value. Retrying is pointless and would
   *   bury the fix behind an endless reconnect loop, so the client halts and
   *   says what to do.
   * - `version`: the extension and the plugin are not from the same release.
   *   Also halted, because no retry can change a build.
   * - `rate-limit`: temporary by definition. Backoff continues, more slowly.
   *
   * @param reason - the reason the bridge gave.
   */
  private async onRejected(reason: RejectReason): Promise<void> {
    this.clearTimers()

    if (reason === 'token') {
      this.halted = true
      this.teardownSocket('token rejected')
      await this.writeStatus('unauthorized', 'The bridge rejected the pairing token. Copy the current token from the DSH plugin settings and paste it here again.', null)
      return
    }
    if (reason === 'version') {
      this.halted = true
      this.teardownSocket('protocol mismatch')
      await this.writeStatus('incompatible', `The bridge speaks a different protocol version than this extension (extension v${PROTOCOL_VERSION}). Update the extension and the DSH plugin together.`, null)
      return
    }

    this.teardownSocket('rate limited')
    void this.scheduleRetry('The bridge is rate-limiting this extension.', 'reconnecting')
  }

  /**
   * Finish a batch submission.
   *
   * @param batchId - the acknowledged batch.
   * @param ok - whether the bridge accepted it.
   * @param message - the bridge's explanation when it did not.
   */
  private async onSubmitAck(batchId: string, ok: boolean, message: string | undefined): Promise<void> {
    if (this.pendingBatchId === batchId) {
      this.pendingBatchId = null
      await this.clearPending()
    }
    if (ok) {
      this.handlers.onBatchAcked(batchId)
      const current = await this.readStatus()
      await this.env.storage.set({
        [STORAGE_KEYS.status]: { ...current, batchesAcked: current.batchesAcked + 1, updatedAt: this.env.now() },
      })
      return
    }
    this.handlers.onBatchRejected(batchId, message ?? 'The bridge refused the batch.')
  }

  /**
   * Record a failure and schedule the next dial.
   *
   * @param detail - what to show the user.
   * @param state - the state to report while waiting.
   */
  private async scheduleRetry(detail: string, state: ConnectionState): Promise<void> {
    if (this.stopped || this.halted) return
    if (this.retryTimer !== null) return

    // `attempts` counts failures that have already happened, and it is read
    // BEFORE this one is counted so that the first failure waits the first
    // delay. Incrementing first would make the very first retry wait twice as
    // long as intended, and every subsequent one along with it.
    const delay = backoffDelay(this.attempts)
    this.attempts += 1
    const at = this.env.now() + delay

    // The timer is installed BEFORE the status write is awaited. Persisting the
    // status is asynchronous, and a second failure arriving in that window would
    // otherwise see `retryTimer` still null and install a competing timer, which
    // would double the dial rate instead of backing it off.
    this.retryTimer = this.env.setTimeout(() => {
      this.retryTimer = null
      this.dial()
    }, delay)
    this.env.setAlarm('reconnect', { when: at })
    this.env.log('info', `[dsh-annotate] reconnecting in ${delay}ms (attempt ${this.attempts})`)

    // The timer covers the case where the worker is still awake, which is the
    // common one: a bridge restart takes a second, not twenty. The alarm covers
    // the case where it is not.
    await this.writeStatus(state, clip(detail), null, at)
  }

  // -------------------------------------------------------------------------
  // Socket plumbing
  // -------------------------------------------------------------------------

  /**
   * Write a frame, queueing it until the handshake has completed.
   *
   * The queue exists because the interesting frames are produced by the user's
   * click, and a click can land in the few milliseconds between the socket
   * opening and the bridge confirming the handshake. Dropping those frames would
   * mean the first annotation of a session is the one that goes missing.
   *
   * @param message - the frame to write.
   * @returns whether it was written immediately.
   */
  private write(message: ExtensionMessage): boolean {
    const frame = JSON.stringify(message)
    if (!this.greeted || this.socket === null || this.socket.readyState !== SOCKET_OPEN) {
      // Bounded: a queue that grows without a connected socket would grow with
      // every pick the user makes while the bridge is down.
      if (this.outbox.length < 16) this.outbox.push(frame)
      return false
    }
    this.sendRaw(frame)
    return true
  }

  /**
   * Write a frame to a socket known to be open.
   *
   * @param frame - the serialised frame.
   */
  private sendRaw(frame: string): void {
    const socket = this.socket
    if (socket === null || socket.readyState !== SOCKET_OPEN) return
    try {
      socket.send(frame)
    } catch (error: unknown) {
      // A send on a socket that closed between the state check and the call.
      // The close handler owns the reconnect, so this only reports.
      this.env.log('warn', `[dsh-annotate] send failed: ${error instanceof Error ? error.message : String(error)}`)
    }
  }

  /** Write a frame without queueing, for the handshake itself. */
  private sendNow(message: ExtensionMessage): void {
    this.sendRaw(JSON.stringify(message))
  }

  /**
   * Detach and close the socket without scheduling a retry.
   *
   * @param reason - the close reason sent to the bridge.
   */
  private teardownSocket(reason: string): void {
    const socket = this.socket
    this.socket = null
    this.greeted = false
    this.authenticated = false
    this.outbox.length = 0
    this.clearPing()
    this.env.setAlarm('keepalive', null)
    if (socket === null) return
    socket.onopen = null
    socket.onmessage = null
    socket.onclose = null
    socket.onerror = null
    try {
      socket.close(1000, reason)
    } catch {
      // Nothing to do: the socket is already gone.
    }
  }

  /** Start the liveness probe. */
  private startPing(): void {
    this.clearPing()
    this.pingTimer = this.env.setInterval(() => { this.ping() }, PING_INTERVAL_MS)
  }

  /** Stop the liveness probe. */
  private clearPing(): void {
    if (this.pingTimer === null) return
    this.env.clearInterval(this.pingTimer)
    this.pingTimer = null
  }

  /** Cancel every timer this client owns. */
  private clearTimers(): void {
    if (this.retryTimer !== null) {
      this.env.clearTimeout(this.retryTimer)
      this.retryTimer = null
    }
    this.clearPing()
  }

  // -------------------------------------------------------------------------
  // Durable state
  // -------------------------------------------------------------------------

  /**
   * Read the status record, falling back to the initial one.
   *
   * @returns the stored status, or {@link INITIAL_STATUS}.
   */
  private async readStatus(): Promise<BridgeStatus> {
    const stored = await this.env.storage.get(STORAGE_KEYS.status)
    return readStatusRecord(stored[STORAGE_KEYS.status])
  }

  /**
   * Merge a transition into the status record and persist it.
   *
   * Every field is written on every transition rather than patched, because the
   * previous record may be from an older build of the extension and a partial
   * update would leave the settings page rendering a shape that no longer
   * exists.
   *
   * @param state - the new connection state.
   * @param detail - explanation for the user, already bounded.
   * @param bridgeVersion - the bridge's protocol version, when known.
   * @param nextAttemptAt - when the next dial is due, when one is scheduled.
   */
  private async writeStatus(
    state: ConnectionState,
    detail: string | null,
    bridgeVersion: number | null,
    nextAttemptAt: number | null = null,
  ): Promise<void> {
    const now = this.env.now()
    const previous = await this.readStatus()
    const status: BridgeStatus = {
      state,
      detail,
      connectedAt: state === 'connected' ? now : previous.connectedAt,
      nextAttemptAt,
      attempts: this.attempts,
      bridgeVersion: bridgeVersion ?? previous.bridgeVersion,
      batchesAcked: previous.batchesAcked,
      updatedAt: now,
    }
    await this.env.storage.set({ [STORAGE_KEYS.status]: status })
  }

  /** Drop the stored in-flight batch. */
  private async clearPending(): Promise<void> {
    await this.env.storage.remove(PENDING_BATCH_KEY)
  }
}

/**
 * Read the close code out of a close event.
 *
 * The event is typed as unknown because the platform's `CloseEvent` is not
 * guaranteed present in a worker's lib set; the code is the only field used, and
 * an absent one is reported as absent rather than as zero.
 *
 * @param event - the close event.
 * @returns the close code, or `null`.
 */
function closeCodeOf(event: unknown): number | null {
  if (!isRecord(event)) return null
  const code = event['code']
  return typeof code === 'number' ? code : null
}

/**
 * Recover a pending batch from storage.
 *
 * The stored value is validated rather than trusted: it was written by an
 * earlier build of this extension, and a shape change must degrade to "no
 * pending batch" instead of throwing inside a worker start.
 *
 * @param value - the raw stored value.
 * @returns the pending batch, or `null`.
 */
export function readPendingBatch(value: unknown): PendingBatch | null {
  if (!isRecord(value)) return null
  const attempts = value['attempts']
  const tabId = value['tabId']
  if (typeof attempts !== 'number' || !Number.isInteger(attempts) || attempts < 0) return null
  if (typeof tabId !== 'number' || !Number.isInteger(tabId)) return null
  const batch = value['batch']
  // The protocol's own guard runs here, not a local restatement of it: a stored
  // batch that no longer validates is dropped now rather than sent and refused
  // by the bridge, and using the same predicate means the two can never drift.
  if (!isAnnotationBatch(batch)) return null
  return { batch, tabId, attempts }
}

/**
 * Recover a status record from storage.
 *
 * @param value - the raw stored value.
 * @returns the record, or {@link INITIAL_STATUS} when it is missing or unusable.
 */
export function readStatusRecord(value: unknown): BridgeStatus {
  if (!isRecord(value)) return INITIAL_STATUS
  const state = value['state']
  if (!isConnectionState(state)) return INITIAL_STATUS
  const detail = value['detail']
  const connectedAt = value['connectedAt']
  const nextAttemptAt = value['nextAttemptAt']
  const attempts = value['attempts']
  const bridgeVersion = value['bridgeVersion']
  const batchesAcked = value['batchesAcked']
  const updatedAt = value['updatedAt']
  return {
    state,
    detail: typeof detail === 'string' ? detail : null,
    connectedAt: typeof connectedAt === 'number' ? connectedAt : null,
    nextAttemptAt: typeof nextAttemptAt === 'number' ? nextAttemptAt : null,
    attempts: typeof attempts === 'number' ? attempts : 0,
    bridgeVersion: typeof bridgeVersion === 'number' ? bridgeVersion : null,
    batchesAcked: typeof batchesAcked === 'number' ? batchesAcked : 0,
    updatedAt: typeof updatedAt === 'number' ? updatedAt : 0,
  }
}

/**
 * Whether a value is one of the connection states.
 *
 * @param value - candidate state.
 * @returns whether it is a known state.
 */
export function isConnectionState(value: unknown): value is ConnectionState {
  return value === 'unpaired'
    || value === 'connecting'
    || value === 'connected'
    || value === 'reconnecting'
    || value === 'unauthorized'
    || value === 'incompatible'
}

/**
 * A human sentence describing a state, for the settings page and the badge.
 *
 * @param status - the record to describe.
 * @returns a short, secret-free description.
 */
export function describeStatus(status: BridgeStatus): string {
  switch (status.state) {
    case 'unpaired':
      return 'Not paired. Paste the token from the DSH plugin settings to connect.'
    case 'connecting':
      return 'Connecting to the local bridge…'
    case 'connected':
      return 'Connected. Picking is available.'
    case 'reconnecting':
      return status.detail ?? 'Reconnecting to the local bridge…'
    case 'unauthorized':
      return status.detail ?? 'The bridge rejected the pairing token.'
    case 'incompatible':
      return status.detail ?? 'The extension and the bridge speak different protocol versions.'
  }
}
